INSERT INTO ROLE (NAME, CAN_WATCH_CONTACT_INFO,
                  CAN_CHANGE_CITY,
                  CAN_SUBMIT_REQUEST,
                  CAN_WATCH_SELF_REQUESTS,
                  CAN_OPERATE_SELF_REQUESTS,
                  CAN_WATCH_ALL_REQUESTS,
                  CAN_OPERATE_ALL_REQUESTS,
                  CAN_OPERATE_ADVERTS) VALUES ('Гость',
                                               FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROLE (NAME, CAN_WATCH_CONTACT_INFO,
                  CAN_CHANGE_CITY,
                  CAN_SUBMIT_REQUEST,
                  CAN_WATCH_SELF_REQUESTS,
                  CAN_OPERATE_SELF_REQUESTS,
                  CAN_WATCH_ALL_REQUESTS,
                  CAN_OPERATE_ALL_REQUESTS,
                  CAN_OPERATE_ADVERTS) VALUES ('Пользователь',
                                               TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE);
INSERT INTO ROLE (NAME, CAN_WATCH_CONTACT_INFO,
                  CAN_CHANGE_CITY,
                  CAN_SUBMIT_REQUEST,
                  CAN_WATCH_SELF_REQUESTS,
                  CAN_OPERATE_SELF_REQUESTS,
                  CAN_WATCH_ALL_REQUESTS,
                  CAN_OPERATE_ALL_REQUESTS,
                  CAN_OPERATE_ADVERTS) VALUES ('Администратор',
                                               FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE);
INSERT INTO ROLE (NAME, CAN_WATCH_CONTACT_INFO,
                  CAN_CHANGE_CITY,
                  CAN_SUBMIT_REQUEST,
                  CAN_WATCH_SELF_REQUESTS,
                  CAN_OPERATE_SELF_REQUESTS,
                  CAN_WATCH_ALL_REQUESTS,
                  CAN_OPERATE_ALL_REQUESTS,
                  CAN_OPERATE_ADVERTS) VALUES ('Специалист',
                                               TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE);